### PR TITLE
Apple homepage feature branch

### PR DESCRIPTION
**Pull request by mosesmuchemi**

### CODE REVIEW

**Review by stratospherique — COMMENTED** [review]
### Pull request under review by Ahmed Mahfoudh TSE

**Review by stratospherique — CHANGES_REQUESTED** [review]
### Great work @mosesmuchemi  :clap: . Almost done. You just need to fix the issue below :arrow_down: 

image

- **[REQUIRED]** These images are supposed to act as links. You should wrap each `img` inside an `<a>` element :nerd_face: 

### That's it :relieved: . When finished, kindly resubmit another code review form :pray:

**Comment by mosesmuchemi** [comment]
I have now wrapped the images with anchor tags to make them clickable as recommended by @stratospherique

**Review by Redvanisation — APPROVED** [review]
### Hello @mosesmuchemi ⭐️  

### _Nice work on this project, it seems that you have met the requirements so I am approving your project. 👍_ 

### You may merge to master and submit a project completion form. 🚀 

### Good luck! 🍀

**Pull request merged**
